# We are using the ionicons icon set https://ionic.io/ionicons

HEADER:
  label: "Show Contacts"

USER:
  role: "Master's Thesis Researcher – Digital Twin & 5G Localization"
  name: "Nima Chaharbaghi"
  username: "nimachaharbaghi"
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "nima.chaharbaghi@eleve.isep.fr"
    icon: "mail-outline"
  - label: "Location"
    value: "Paris, France"
    icon: "location-outline"
  - label: "Affiliation"
    value: "EURECOM, Sophia Antipolis"
    icon: "school-outline"

SOCIAL:
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/in/nima-chaharbaghi-2aa283125/"
  - icon: "logo-github"
    url: "https://github.com/nimachaharbaghi"
  - icon: "mail-outline"
    url: "mailto:nimachaharbaghi@gmail.com"
